<?php

declare(strict_types=1);

namespace App\Services\Mail;

use App\Models\MailAccount;
use InvalidArgumentException;

/**
 * Renders a per-account mbsync (isync) configuration that mirrors ONE IMAP
 * mailbox into a local Maildir tree, read-only-origin and pull-only. This is
 * the single, auditable place where that invariant is enforced in text form
 * — every directive that could let a sync WRITE to or DELETE from the origin
 * mailbox is nailed down explicitly rather than left to a default:
 *
 *   - `Sync Pull`       — far (IMAP) → near (Maildir) only. Never `Push`/`Both`.
 *   - `Create Near`     — new local Maildir folders may be created to mirror
 *                          the server's folder list. Never `Far`/`Both`.
 *   - `Expunge None`    — never expunge messages flagged \Deleted on either side.
 *   - `Remove None`     — never remove a message that disappeared on one side.
 *   - `CopyArrivalDate` — the archived copy's mtime matches the message's
 *                          original arrival date, not the sync time.
 *
 * The account's IMAP password is NEVER written into the generated file. It is
 * fetched at mbsync's own auth time via `PassCmd`, which shells the minimal
 * `php artisan mail:account-password {id}` helper (see PrintMailAccountPassword)
 * that decrypts MailAccount::password (the model's `encrypted` cast) and prints
 * it to stdout for mbsync to read from the pipe. The config file therefore only
 * ever contains the account's numeric ID — never the secret itself.
 *
 * TLS is pinned per the account's configured `encryption` and never silently
 * downgraded to plaintext: an unrecognised encryption value is a hard error
 * (see tlsType()) rather than a fallback to `TLSType None`.
 *
 * `render()` is a pure string builder — no filesystem/network/database access
 * beyond reading the given $account's already-loaded attributes.
 */
final class MbsyncConfig
{
    public function render(MailAccount $account, string $stateDir, string $maildirDir): string
    {
        $id = 'll_'.$account->id;
        $stateDir = rtrim($stateDir, '/').'/';
        $maildirDir = rtrim($maildirDir, '/');

        $lines = [
            '# Generated by App\Services\Mail\MbsyncConfig — DO NOT EDIT.',
            '# Regenerated fresh on every sync run. Pull-only, read-only-origin',
            '# mirror: this config must never gain a Push direction, a Both/Far',
            '# Create, or a Both/Far/Near Expunge/Remove — any of those would let',
            '# a sync mutate or delete mail on the origin mailbox.',
            '',
            "IMAPAccount {$id}",
            'Host '.$this->quote((string) $account->host),
            'Port '.(int) $account->port,
            'User '.$this->quote((string) $account->username),
            // The password itself never appears in this file — see class docblock.
            $this->passCmd($account),
            // isync >= 1.5.0 renamed SSLType/SSLVersions to TLSType/TLSVersions.
            // `+1.2 +1.3` pins TLS >= 1.2 (only 1.2/1.3 enabled).
            'TLSType '.$this->tlsType((string) $account->encryption),
            'TLSVersions +1.2 +1.3',
            '',
            "IMAPStore {$id}-remote",
            "Account {$id}",
            '',
            "MaildirStore {$id}-local",
            'Path '.$this->quote($maildirDir.'/'),
            'Inbox '.$this->quote($maildirDir.'/INBOX'),
            'SubFolders Verbatim',
            '',
            "Channel {$id}",
            "Far :{$id}-remote:",
            "Near :{$id}-local:",
            $this->patterns($account->folders),
            // Read-only origin: the Far (IMAP) side is never written to, ever.
            'Create Near',
            'Expunge None',
            'Remove None',
            'CopyArrivalDate yes',
            'Sync Pull',
            'SyncState '.$this->quote($stateDir),
            '',
        ];

        return implode("\n", $lines);
    }

    /**
     * The mbsync channel name this account's config uses (single channel per
     * config file, selected wholesale by MbsyncRunner via `mbsync -a`).
     */
    public static function channelName(MailAccount $account): string
    {
        return 'll_'.$account->id;
    }

    /**
     * The PassCmd line: shells `php artisan mail:account-password {id}` so
     * mbsync obtains the decrypted password from that command's stdout at auth
     * time, never from a value written into this file.
     */
    private function passCmd(MailAccount $account): string
    {
        $shell = sprintf(
            '%s %s mail:account-password %d',
            escapeshellarg(PHP_BINARY),
            escapeshellarg(base_path('artisan')),
            (int) $account->id,
        );

        return 'PassCmd '.$this->quote($shell);
    }

    /**
     * Map the account's `encryption` column to mbsync's `TLSType` values. An
     * unrecognised value is a hard error (fail closed) rather than a fallback to
     * `TLSType None` — silently downgrading to plaintext on bad input would be
     * the one real security regression this method could introduce.
     */
    private function tlsType(string $encryption): string
    {
        return match ($encryption) {
            'ssl', 'tls' => 'IMAPS',
            'starttls' => 'STARTTLS',
            'none' => 'None',
            default => throw new InvalidArgumentException("Unsupported mail account encryption: {$encryption}"),
        };
    }

    /**
     * `Patterns` restricts the sync to the account's configured folder list;
     * with no restriction configured, every folder on the account is synced.
     * Control characters (config-line-injection vector) are rejected up front by
     * quote(); glob-operator characters are a benign matching quirk, not a
     * security issue (read-only-origin is enforced by the pull-only directives).
     *
     * @param  ?array<int, string>  $folders
     */
    private function patterns(?array $folders): string
    {
        $names = array_values(array_filter(
            $folders ?? [],
            static fn (mixed $f): bool => is_string($f) && $f !== '',
        ));

        if ($names === []) {
            return 'Patterns *';
        }

        return 'Patterns '.implode(' ', array_map($this->quote(...), $names));
    }

    /**
     * Quote a value for embedding as an mbsync config string literal.
     *
     * SECURITY: the rendered config is line-oriented (`implode("\n", …)`), so a
     * value containing a newline (or other control character) would break out of
     * its quoted string and inject arbitrary PHYSICAL config lines — a PoC
     * injected `Sync Both` / `Expunge Both`, flipping the mirror into one that
     * WRITES/DELETES the origin mailbox. Control characters have no legitimate
     * place in a host / username / folder name, so we FAIL CLOSED: any value
     * containing NUL, a C0 control (incl. `\n`/`\r`), or DEL makes render() throw
     * before any config is produced. The message never echoes the value.
     *
     * @throws InvalidArgumentException if $value contains a control character
     */
    private function quote(string $value): string
    {
        if (preg_match('/[\x00-\x1f\x7f]/', $value) === 1) {
            throw new InvalidArgumentException(
                'Refusing to render mbsync config: an account value contains a disallowed control character.'
            );
        }

        return '"'.str_replace(['\\', '"'], ['\\\\', '\\"'], $value).'"';
    }
}
