<?php

declare(strict_types=1);

namespace App\Services\Mail;

use App\Models\MailAccount;
use InvalidArgumentException;

/**
 * Renders a per-account mbsync (isync) configuration that mirrors ONE IMAP
 * mailbox into a local Maildir tree, read-only-origin and pull-only. This is
 * the single, auditable place where that invariant is enforced in text form
 * — every directive that could let a sync WRITE to or DELETE from the origin
 * mailbox is nailed down explicitly rather than left to a default:
 *
 *   - `Sync Pull`       — far (IMAP) → near (Maildir) only. Never `Push`/`Both`.
 *   - `Create Near`     — new local Maildir folders may be created to mirror
 *                          the server's folder list. Never `Far`/`Both` (which
 *                          would let a sync CREATE mailboxes on the server).
 *   - `Expunge None`    — never expunge (permanently remove) messages flagged
 *                          \Deleted on either side.
 *   - `Remove None`     — never remove a message that disappeared on one side
 *                          from the other. A message the archive already has
 *                          is never deleted because it vanished upstream.
 *   - `CopyArrivalDate` — the archived copy's mtime matches the message's
 *                          original arrival date, not the sync time.
 *
 * The account's IMAP password is NEVER written into the generated file. It is
 * fetched at mbsync's own auth time via `PassCmd`, which shells a minimal,
 * dedicated `php artisan mail:account-password {id}` helper
 * (see PrintMailAccountPassword) that decrypts MailAccount::password
 * (the model's `encrypted` cast) and prints it to stdout for mbsync to read
 * directly from the pipe. The config file therefore only ever contains the
 * account's numeric ID — never the secret itself.
 *
 * TLS is pinned per the account's configured `encryption` and never silently
 * downgraded to plaintext: an unrecognised encryption value is a hard error
 * (see tlsType()) rather than a fallback to `TLSType None`.
 *
 * `render()` is a pure string builder — it does not touch the filesystem,
 * the network, or the database beyond reading the given $account's already-
 * loaded attributes. MbsyncRunner owns writing the result to a transient
 * temp file and actually invoking the mbsync binary.
 */
final class MbsyncConfig
{
    /**
     * @param  MailAccount  $account  the account to sync; only host/port/
     *                                username/encryption/id/folders are read
     *                                — the password is intentionally never
     *                                touched here (see class docblock)
     * @param  string  $stateDir  a directory (already created by the caller)
     *                            where mbsync persists its UIDVALIDITY/UID
     *                            sync-state files across runs. This MUST be a
     *                            durable path on the scratch volume, never a
     *                            temp directory that gets wiped between runs
     *                            — losing it forces a full, redundant re-pull
     *                            (harmless but wasteful; it does NOT risk
     *                            origin data, since this whole config is
     *                            pull-only).
     * @param  string  $maildirDir  a directory (already created by the
     *                              caller) that mbsync mirrors the mailbox
     *                              into. MaildirIngestor reads from here and
     *                              shreds each message file once it is
     *                              durably archived.
     */
    public function render(MailAccount $account, string $stateDir, string $maildirDir): string
    {
        $id = 'll_'.$account->id;
        $stateDir = rtrim($stateDir, '/').'/';
        $maildirDir = rtrim($maildirDir, '/');

        $lines = [
            '# Generated by App\Services\Mail\MbsyncConfig — DO NOT EDIT.',
            '# Regenerated fresh on every sync run. Pull-only, read-only-origin',
            '# mirror: this config must never gain a Push direction, a Both/Far',
            '# Create, or a Both/Far/Near Expunge/Remove — any of those would let',
            '# a sync mutate or delete mail on the origin mailbox.',
            '',
            "IMAPAccount {$id}",
            'Host '.$this->quote((string) $account->host),
            'Port '.(int) $account->port,
            'User '.$this->quote((string) $account->username),
            // The password itself never appears in this file — see class docblock.
            $this->passCmd($account),
            // isync >= 1.5.0 renamed SSLType/SSLVersions to TLSType/TLSVersions
            // (the old names still parse but emit a deprecation notice), and the
            // version list changed to the additive `+<ver>` form — `TLSVersions
            // TLSv1.2 TLSv1.3` is REJECTED by 1.5.x ("Unrecognized TLS version").
            // The deploy image ships isync 1.5.1 (Alpine 3.24), so we emit the
            // new directives directly. `+1.2 +1.3` pins TLS >= 1.2 (only 1.2/1.3
            // enabled), same intent as the old `TLSv1.2 TLSv1.3`.
            'TLSType '.$this->tlsType((string) $account->encryption),
            'TLSVersions +1.2 +1.3',
            '',
            "IMAPStore {$id}-remote",
            "Account {$id}",
            '',
            "MaildirStore {$id}-local",
            'Path '.$this->quote($maildirDir.'/'),
            'Inbox '.$this->quote($maildirDir.'/INBOX'),
            'SubFolders Verbatim',
            '',
            "Channel {$id}",
            "Far :{$id}-remote:",
            "Near :{$id}-local:",
            $this->patterns($account->folders),
            // Read-only origin: the Far (IMAP) side is never written to, ever.
            'Create Near',
            'Expunge None',
            'Remove None',
            'CopyArrivalDate yes',
            'Sync Pull',
            'SyncState '.$this->quote($stateDir),
            '',
        ];

        return implode("\n", $lines);
    }

    /**
     * The mbsync channel name this account's config uses (single channel per
     * config file, selected wholesale by MbsyncRunner via `mbsync -a`).
     */
    public static function channelName(MailAccount $account): string
    {
        return 'll_'.$account->id;
    }

    /**
     * The PassCmd line: shells `php artisan mail:account-password {id}` so
     * mbsync obtains the decrypted password from that command's stdout at
     * auth time, never from a value written into this file. Both the PHP
     * binary path and the artisan script path are shell-escaped (defensive —
     * in a self-hosted single-tenant deploy neither ever contains shell
     * metacharacters, but this costs nothing and removes the assumption);
     * the account ID is a plain integer, never quoted/escaped input.
     */
    private function passCmd(MailAccount $account): string
    {
        $shell = sprintf(
            '%s %s mail:account-password %d',
            escapeshellarg(PHP_BINARY),
            escapeshellarg(base_path('artisan')),
            (int) $account->id,
        );

        return 'PassCmd '.$this->quote($shell);
    }

    /**
     * Map the account's `encryption` column to mbsync's `TLSType` values.
     * `ssl` and `tls` both mean "encrypt from the first byte of the
     * connection" vs. `starttls`'s "connect plaintext, then upgrade" — mbsync
     * only exposes two secure transports (IMAPS = implicit, STARTTLS =
     * opportunistic), so `ssl` and `tls` map to the same IMAPS transport and
     * `starttls` maps to STARTTLS. An unrecognised value is a hard error
     * (fail closed) rather than a fallback to `TLSType None` — silently
     * downgrading to plaintext on bad input would be the one real security
     * regression this method could introduce. (The IMAPS / STARTTLS / None
     * VALUES are unchanged from the pre-1.5.0 SSLType keyword; only the
     * directive name was renamed — verified against isync 1.5.1.)
     */
    private function tlsType(string $encryption): string
    {
        return match ($encryption) {
            'ssl', 'tls' => 'IMAPS',
            'starttls' => 'STARTTLS',
            'none' => 'None',
            default => throw new InvalidArgumentException("Unsupported mail account encryption: {$encryption}"),
        };
    }

    /**
     * `Patterns` restricts the sync to the account's configured folder list;
     * with no restriction configured, every folder on the account is synced.
     *
     * IMPORTANT: isync `Patterns` values are IMAP GLOB patterns, not literal
     * strings. Quoting (see quote()) only lets a name contain spaces / `"` /
     * `\` safely — it does NOT disable glob-operator semantics, and isync
     * provides no documented escape for a literal `*` / `%` / `!` inside a
     * pattern. So a configured folder name that itself contains `*`/`%`/`!`
     * is matched as a glob and may over- or under-match (e.g. `In*` would
     * also match `Inbox-archive`). This is a benign matching quirk, not a
     * security issue: the read-only-origin guarantee is enforced by the
     * pull-only Channel directives regardless of which folders match. Control
     * characters, which WOULD be a security issue (config-line injection),
     * are rejected up front by quote().
     *
     * @param  ?array<int, string>  $folders
     */
    private function patterns(?array $folders): string
    {
        $names = array_values(array_filter(
            $folders ?? [],
            static fn (mixed $f): bool => is_string($f) && $f !== '',
        ));

        if ($names === []) {
            return 'Patterns *';
        }

        return 'Patterns '.implode(' ', array_map($this->quote(...), $names));
    }

    /**
     * Quote a value for embedding as an mbsync config string literal.
     *
     * SECURITY: the rendered config is line-oriented (`implode("\n", …)`), so
     * a value containing a newline (or other control character) would break
     * out of its quoted string and inject arbitrary PHYSICAL config lines —
     * a PoC injected `Sync Both` / `Expunge Both` / `Create Both`, flipping
     * the mirror into one that WRITES/DELETES the origin mailbox and defeating
     * this class's whole reason to exist. Control characters have no
     * legitimate place in a host / username / folder name, so we FAIL CLOSED:
     * any value containing NUL, a C0 control (incl. `\n`/`\r`), or DEL makes
     * render() throw before any config can be produced. The exception message
     * deliberately does NOT echo the offending value (no leak into logs /
     * last_error).
     *
     * With control characters excluded, backslash and double-quote are the
     * only two characters isync's config parser treats specially inside a
     * double-quoted string, so escaping exactly those two is sufficient and
     * exact.
     *
     * @throws InvalidArgumentException if $value contains a control character
     */
    private function quote(string $value): string
    {
        if (preg_match('/[\x00-\x1f\x7f]/', $value) === 1) {
            throw new InvalidArgumentException(
                'Refusing to render mbsync config: an account value contains a disallowed control character.'
            );
        }

        return '"'.str_replace(['\\', '"'], ['\\\\', '\\"'], $value).'"';
    }
}
